@Kiikiiworld_Api_HostAddress = http://localhost:5199

GET {{Kiikiiworld_Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Kiikiiworld_Api_HostAddress}}/posts
Accept: text/plain

###

POST {{Kiikiiworld_Api_HostAddress}}/posts
Content-Type: application/json

{
  "kind": "Quote",
  "title": "On persistence",
  "body": "Fall seven times, stand up eight."
}

