using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kiikiiworld.Api.Data.Migrations
{
    /// <inheritdoc />
    public partial class SeedPostsFromCsv : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Only seed a fresh database: capture whether Posts is empty before inserting anything.
            migrationBuilder.Sql("CREATE TEMP TABLE SeedGuard AS SELECT NOT EXISTS (SELECT 1 FROM Posts) AS ShouldSeed;");

            // The posts below reference these by name, so make sure they exist before UseSeeding runs.
            foreach (var name in new[] { "Photo", "Video", "Quote", "Story", "Audio" })
            {
                migrationBuilder.Sql($"""
                    INSERT INTO PostTypes (Name)
                    SELECT {Text(name)}
                    WHERE NOT EXISTS (SELECT 1 FROM PostTypes WHERE Name = {Text(name)});
                    """);
            }

            foreach (var post in SeedPosts)
            {
                migrationBuilder.Sql($"""
                    INSERT INTO Posts (CreatedAt, UpdatedAt, Hidden, PostTypeId, Title, Body)
                    SELECT {Text(post.CreatedAt)}, {Text(post.CreatedAt)}, {(post.Hidden ? 1 : 0)},
                        (SELECT Id FROM PostTypes WHERE Name = {Text(post.Type)} LIMIT 1),
                        {Text(post.Title)}, {Text(post.Body)}
                    WHERE (SELECT ShouldSeed FROM temp.SeedGuard);
                    """);

                if (post.MediaUrl is not null)
                {
                    // Ids are generated by the db, so link the media to the post that was just inserted.
                    migrationBuilder.Sql($"""
                        INSERT INTO Media (Type, Title, Url, PostId)
                        SELECT {Text(post.MediaType)}, {Text(post.Title)}, {Text(post.MediaUrl)}, last_insert_rowid()
                        WHERE (SELECT ShouldSeed FROM temp.SeedGuard);
                        """);
                }
            }

            migrationBuilder.Sql("DROP TABLE temp.SeedGuard;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally empty: seeded posts may have been edited since, so rolling back leaves the data alone.
        }

        private static string Text(string value) =>
            value is null ? "NULL" : $"'{value.Replace("'", "''")}'";

        private sealed record SeedPost(
            string Type, string CreatedAt, string Title, bool Hidden,
            string Body = null, string MediaType = null, string MediaUrl = null);

        private static SeedPost Quote(string createdAt, string title, string body, bool hidden = false) =>
            new("Quote", createdAt, title, hidden, Body: body);

        private static SeedPost Story(string createdAt, string title, string body, bool hidden = false) =>
            new("Story", createdAt, title, hidden, Body: body);

        private static SeedPost Photo(string createdAt, string title, string url, bool hidden = false) =>
            new("Photo", createdAt, title, hidden, MediaType: "Image", MediaUrl: url);

        private static SeedPost Video(string createdAt, string title, string url, bool hidden = false) =>
            new("Video", createdAt, title, hidden, MediaType: "Video", MediaUrl: url);

        // Imported from import_data/seed_data.csv. The original UUIDs are discarded; SQLite generates the ids.
        private static readonly SeedPost[] SeedPosts =
        [
            Quote("2020-04-05 12:00:00", "Henry David Thoreau ~ Walden", "I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived."),
            Quote("2020-04-15 12:00:00", "jed mckenna", "When we believe in the world outside of ourselves, gain is often perceived as good and loss as bad. When we stop believing in a world external to self. that reverses: gain becomes bad and loss becomes good. Nothing we can lose was ever ours in the first place. All we can ever lose is illusion."),
            Quote("2020-06-23 12:00:00", "jed mckenna", "We slip into the lives that are laid out for us the way children slip into the clothes their mother lays out for them in the morning. No one decides. We don't live our lives by choice, but by default."),
            Quote("2020-12-01 12:00:00", "quotes on death", """
                ## Memento Mori

                To begin depriving death of it's greatest advantage over us, let us adopt a way clean contrary to that of the common one; let us deprive death of it's strageness, let us frequent it, let us get used to it; let us have nothing more often in mind than death. We do not know where death await us: so let us wait for it everywhere. To practice death is to practice freedom. A man who has learned how to die has unlearned how to be a slave.\
                `michel de montaigne`

                first you have to know, not fear, know. that some day you're gonna die.. It's only after we lost everything that we're free to anything.\
                `fight club @1:02:16`

                One of the illusions of life is that the present hour is not the critical, decisive hour. Write it on your heart that every day is the best day in the year. No man has learned anything rightly, until he knows that every day is Doomsday.\
                `ralph waldo emerson`

                Awareness of death is the very bedrock of the entire path. Until you have developed this awareness, all other practices are obstructed.\
                `Dalai lama`

                I have formed during the last few years such a close relationship with this best and truest friend of mankind that death’s image is not only no longer terrifying to me, but is indeed very soothing and consoling, and I thank my God for graciously granting me the opportunity of learning that death is the key which unlocks the door to our true happiness.\
                `mozart`

                There is but one truly serious philosophical problem and that is suicide. Judging whether life is or is not worth living amounts to answering the fundamental question of philosophy. All the rest — whether or not the world has three dimensions, whether the mind has nine or twelve categories — comes afterwards. These are games; one must first answer.\
                `albert camus`

                Death smiles at us all. All a man can do is smile back\
                `marcus aurelius`

                to face the fact that you are completely alone and to accept that you are alone is to accept death\
                `my dinner with andre @1:46:00`
                """),
            Quote("2022-07-15 12:00:00", "ragnar lothbrok ~ vikings s4 e15", "It gladdens me to know that Odin prepares for a feast. Soon I shall be drinking ale from curved horns. This hero that comes into Valhalla does not lament his death! I shall not enter Odin's hall with fear."),
            Quote("2022-07-23 12:00:00", "tao te ching verse 48", """
                ## The illusion of control

                you need to forget about what you know,\
                hitting bottom is not a fucking weekend retreat\
                its not a god damn seminenar.\
                Stop trying to control everything and just let go.\
                `fight club @1:38:42`


                In pursuit of knowledge,
                every day something is added.\
                In the practice of the Tao,
                every day something is dropped.\
                Less and less do you need to force things,
                until finally you arrive at non-action.\
                When nothing is done,
                nothing is left undone.

                True mastery can be gained
                by letting things go their own way.\
                It can't be gained by interfering.

                """),
            Quote("2023-06-17 12:00:00", "buddhism", "In Buddhist philosophy, Māyā is invoked as one of twenty subsidiary unwholesome mental factors, responsible for deceit or concealment about the nature of things."),
            Quote("2023-12-21 12:00:00", "Tao Te Ching ~ verse 5", """
                Heaven and Earth are impartial;\
                They see the ten thousand things as straw dogs.\
                The wise are impartial;\
                They see the people as straw dogs.\
                \
                The space between heaven and Earth is like a bellows.\
                The shape changes but not the form;\
                The more it moves, the more it yields.\
                More words count less.\
                \
                Hold fast to the center.
                """),
            Quote("2024-05-26 12:00:00", "youtube user @cr01554nt", "when prayer becomes a habit, miracles become a lifestyle"),
            Quote("2024-07-09 12:00:00", "henry david thoreau ~ walden", "We must learn to reawaken and keep ourselves awake, not by mechanical aids, but by an infinite expectation of the dawn, which does not forsake us even in our soundest sleep. I know of no more encouraging fact than the unquestionable ability of man to elevate his life by a conscious endeavour. It is something to be able to paint a particular picture, or to carve a statue, and so to make a few objects beautiful; but it is far more glorious to carve and paint the very atmosphere and medium through which we look, which morally we can do. To affect the quality of the day, that is the highest of arts."),
            Quote("2024-08-23 12:00:00", "if truth be told ~ book", "That's the thing with baggage - you get used to carrying it around. You know it's heavy but the weight has a way of becoming a part of your life. Only when you take it off your back and feel the lightness does the awareness of the load hit you."),
            Quote("2024-09-11 12:00:00", "if truth be told ~ book", "Beauty does not lie in the eyes of the beholder but in the mind of the perceiver. The cleaner the mind, the greater the beauty; the quieter the mind, the more enduring the experience."),
            Quote("2024-09-18 12:00:00", "bad trip on lsd ~ hiab-x", "I noticed a cross which had a festering pile of bloody guts and organs spread across it, staining the wood in crimson. The guts were smothered in wasps, stinging the ruined flesh causing venomous pestles. It was an image of impossible pain, and then the monologue returned, booming over the sirens, droning over the wasps: 'this is Christ; he is still suffering for your sins, still paying the price.'"),
            Quote("2024-09-21 12:00:00", "bumpersticker", "Relax, nothing is under control."),
            Quote("2024-11-05 12:00:00", "Deus Ex: Human Revolution Trailer", "It's not the end of the world, but you can see it from here."),
            Quote("2024-11-22 16:00:00", "growth of the soil ~ knut hamsun", "The settlers didn't make themselves suffer on account of goodies they hadn't got: art, newspapers, luxuries, politics were worth exactly as much as people were willing to pay for them, no more; the growth of the soil, on the other hand, had to be procured at any cost. It was the origin of all things, the only source. the settlers' lives sad and empty? Ho, that least of all! They had their higher powers, their dreams, their loves, their wealth of superstition."),
            Quote("2024-12-08 19:23:00", "amongst white clouds", """
                Climbing up Cold Mountain Path\
                Cold Mountain Road goes on and on\
                A long stream tumbles over boulders\
                a broad valley tangled in green\
                Moss grows thick, but there is no rain\
                pines sing, but there is no wind\
                Who can crawl out from the tangles of this world\
                to sit with me amongst white clouds?
                """),
            Quote("2025-01-29 23:08:00", "подполья ~ Fyodor Dostoevsky", """
                I swear to you, gentlemen, that to be too much aware of things is an illness - a real genuine illness.\
                ~ \
                I even think that the best definition of a man is: an ungrateful creature on two legs.\
                ~ \
                It was "peace" that I wanted - I wanted to be left alone under the floorboards. "Real life", since I was unused to it, crushed me so much that I found it difficult even to breathe.\
                ~\
                And, indeed, I am now asking on my own account an idle question: which is better, cheap happiness or exalted suffering?
                """),
            Quote("2025-03-09 20:40:00", "krishna to arjuna ~ the mahābhārata", """
                look its spring\
                the buds are sweet\
                the water sparkles\
                everyone is joyful\
                we're going to die

                ~

                Victory and defeat are the same. To Act but not to reflect on the fruit of the Act. Seek Detachment. Fight without Desire.
                """),
            Quote("2025-03-31 16:20:00", "~ road to heaven", """
                people eat dirt, dirt eats people\
                `~ 周南山`\
                \
                I'm no saint. I can't transform this world. This world still transforms me.
                """),
            Quote("2025-04-27 15:07:00", "collin mcmorran", """
                Surrender, in the truest sense, is dis-identification with the egoic mind and the collapse of the illusionary Self. \
                ~ \
                We have come to see that true self-enquiry is not a process of adding to your understanding nor is it about personal growth, it is about dropping your story and letting go of your preconceptions, it is about witnessing your mind games with a sort of compassionate detachment.\
                ~\
                Each time you wonder whether you are acting from pure awareness, each time you praise yourself for staying present, each time you are pleased to have controlled your undesirable emotions ‒ you are back in the illusion. Each time you take credit for right thought or right action ‒ you are back in the illusion. So watch for these traps; do not replace an unconscious illusionary Self with a spiritually aware, but conceited, one. Be vigilant and unyielding;\
                ~\
                The assumption is that just as you can learn to play the piano, you can similarly learn to play life. Unfortunately, learning to play life is impossible simply because it is life that is 'playing' you.
                """),
            Quote("2025-09-03 20:00:00", "what is fake spirituality? @1:03:11", "genuine spirituality is about achieving complete sovereignty of mind", hidden: true),
            Quote("2025-09-15 12:00:00", "soliloquized wisdom of a whaler", """
                Is, then, the crown too heavy
                that I wear? this Iron Crown of Lombardy. Yet is it bright with many a gem; i, the wearer, see not its far flashings; but darkly feel that i wear that, that dazzlingly confounds. 'Tis iron --that I know-- not gold.
                """),
            Quote("2025-09-21 22:11:00", "clapped ye eye, matey?", "Want to see what whaling is, eh? Have ye clapped eye on Captain Ahab?"),
            Video("2021-01-14 12:00:00", "new zealand ~ 2020", "https://www.youtube-nocookie.com/embed/JenkjO3Fo4A?si=Goss5_xIukf0TVzo"),
            Video("2024-06-16 12:00:00", "france ~ 2024", "https://www.youtube-nocookie.com/embed/83x5Kj5eERQ?si=N9x_9g1KDlAXy76E"),
            Video("2024-08-14 12:00:00", "arden ~ 08/24", "https://www.youtube-nocookie.com/embed/7nDEFHX5npE?si=TQrendpgu0fZwFVY"),
            Video("2024-09-10 12:40:00", "nørge ~ 24", "https://www.youtube-nocookie.com/embed/r7s_y8mJEBc?si=RnO6WPzzr708PvP5"),
            Video("2025-09-02 20:00:00", "schweiz ~ 2025", "https://www.youtube-nocookie.com/embed/bG9NHQSjInE"),
            Photo("2018-01-20 12:00:00", "sunrise from the holy mountain", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/14.jpg"),
            Photo("2018-01-23 22:31:00", "op safari ~ skiri lanka", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/13.jpg"),
            Photo("2019-12-20 12:00:00", "new camera ~ panasonic g7", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/15.jpg"),
            Photo("2020-02-17 12:00:00", "sittin ~ chandighar", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/8.jpg"),
            Photo("2020-02-19 12:00:00", "late night smoke", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/16.jpg"),
            Photo("2020-03-10 12:00:00", "my room ~ auckland nz", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/10.jpg"),
            Photo("2020-03-17 12:00:00", "first van ~ nz", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/9.jpg"),
            Photo("2020-04-03 12:00:00", "palms ~ nz", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/7.jpg"),
            Photo("2020-04-10 12:00:00", "hut_1 ~ nz", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/11.jpg"),
            Photo("2020-04-14 12:00:00", "hut_2 ~ nz", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/12.jpg"),
            Photo("2020-05-01 12:00:00", "sundown at mountain hut", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/17.jpg"),
            Photo("2020-06-21 10:00:00", "Mt. Teranaki ~ nz", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/3.jpg"),
            Photo("2020-06-29 22:31:00", "dreamscape ~ nz", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/4.jpg"),
            Photo("2020-07-01 12:00:00", "@lakeside", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/18.jpg"),
            Photo("2020-07-12 22:27:00", "fire clouds ~ nz", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/2.jpg"),
            Photo("2021-08-11 12:00:00", "a dream in the works", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/20.png"),
            Photo("2021-08-11 12:00:00", "generational workshop", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/19.png"),
            Photo("2021-09-11 12:00:00", "thinkin ~ switzerland", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/21.jpg"),
            Photo("2022-04-02 15:59:00", "growth ~ auckland nz", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/5.jpg"),
            Photo("2022-05-15 12:00:00", "leef in een droom", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/28.jpg"),
            Photo("2022-06-10 12:00:00", "sven in natural habitat", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/24.jpg"),
            Photo("2022-06-25 12:00:00", "made it out alive", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/30.png"),
            Photo("2022-07-01 12:00:00", "jelte in een droom", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/25.png"),
            Photo("2022-07-05 22:32:00", "drop een rack op een rack", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/27.png"),
            Photo("2022-07-11 12:00:00", "eikesdalsvatnet", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/22.jpg"),
            Photo("2022-07-11 12:00:00", "stacc clouds", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/26.jpg"),
            Photo("2022-07-21 12:00:00", "go slo in norge", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/23.jpg"),
            Photo("2023-06-11 12:00:00", "stacc em intellect edition", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/43.jpg"),
            Photo("2023-11-20 12:00:00", "anti-kraak", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/31.jpg"),
            Photo("2023-12-14 12:00:00", "Amsterdam Lelylaan", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/1.jpg"),
            Photo("2024-01-10 12:00:00", "urban hug", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/44.jpg"),
            Photo("2024-05-08 12:00:00", "brick house ~ morvan, france", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/33.jpg"),
            Photo("2024-05-08 12:00:00", "farms ~ morvan, france", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/32.jpg"),
            Photo("2024-05-14 12:00:00", "dev in van", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/34.png"),
            Photo("2024-06-12 12:00:00", "sunset on a dune ~ haarlem", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/35.jpg"),
            Photo("2024-08-09 12:00:00", "hilly highway ~ arden", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/36.jpg"),
            Photo("2024-08-31 12:00:00", "bunes", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/37.png"),
            Photo("2024-09-01 12:00:00", "fjordland", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/39.png"),
            Photo("2024-09-02 12:00:00", "ed & niklas", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/38.png"),
            Photo("2024-09-06 12:00:00", "creative lookout", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/40.png"),
            Photo("2024-11-04 12:00:00", "sundown ~ Lumix DMC-FS40", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/41.jpg"),
            Photo("2024-11-06 12:00:00", "journey to work ~ Lumix DMC-FS40", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/42.jpg"),
            Photo("2024-11-22 23:16:00", "classic bruckner", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/1000027236.jpg"),
            Photo("2024-12-01 12:40:00", "starz ~ DMC-FS40", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/46.JPG"),
            Photo("2024-12-20 18:35:00", "DMC-FS40 grain", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/P1000120_tiny.jpg"),
            Photo("2024-12-20 18:38:00", "SwitchPrimitive.Root", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/P1000133_tiny.jpg"),
            Photo("2025-02-14 17:09:00", "yarned hangplant 2", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/P1050268%202.JPG", hidden: true),
            Photo("2025-03-30 15:47:00", "lumix g80 ~ 12-32 f/3.5-5.6", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/P1020356-edit-large.jpg"),
            Photo("2025-03-30 16:04:00", "gate to the city ~ leiden", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/P1020311-edit-crop-sml.jpg"),
            Photo("2025-04-15 15:02:00", "average medieval coif user", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/avarage-medival-coif-user.png"),
            Photo("2025-04-24 21:17:00", "me & the missus", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/P1020286-edit-sml.jpg"),
            Photo("2025-04-29 14:36:00", "primordial scream", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/primordial-scream-cow-crop-2.jpg"),
            Photo("2025-04-29 15:08:00", "all THôt's are illusions", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/Screenshot%202025-04-29%20at%2015.10.31.png", hidden: true),
            Photo("2025-05-08 12:00:00", "levels", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/P1020620-edit.jpg"),
            Photo("2025-05-11 12:00:00", "harlem summers", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/P1020678-crop.jpg"),
            Photo("2025-05-12 16:47:00", "vroom vroom", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/1000032202.jpg"),
            Photo("2025-05-15 16:49:00", "shadow of a dutchman", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/1000036502.jpg"),
            Photo("2025-07-04 12:00:00", "movout movin", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/1000036503.jpg"),
            Photo("2025-08-20 21:00:00", "rule 1: always bring a headlamp", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/00-dark-edit.jpg"),
            Photo("2025-08-21 12:00:00", "ancient roofs ~ bern schweiz", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/00-P1030118-edit.jpg"),
            Photo("2025-10-13 12:06:00", "autumn", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/autumn.jpg"),
            Photo("2025-11-04 21:00:00", "bladee ~ 1d", "https://kiikiiworld-serverless-prd-image.s3.eu-central-1.amazonaws.com/P1030283-vibrant-crop.jpg"),
            Story("2000-01-01 12:42:00", "example markdown", "# Test Project Markdown\n\nThis is a link in [Hello World](https://michaelheemskerk.dev/) lorem ipsum dolor sinch gethir this is thext,\n\nThis is a **very bold move** of me.\n\nHello lorem ipsum dolor sinch gethir this is thext,\nwill it morph around the image or will it stay like this.\n\nHello world this is a new scentence.\n\n> This is a blockquote\n\n1. ordered list\n2. this is the second row\n3. third item leggo\n\ndafsadfadfasdf sadf asdf asdf asdf sdf asdf [^1]\n[^1]: This is the footnote. \n\n- first item this is\n- 50.000 items stack em tall\n\nthat was code `const myStatus = 10000;` that was code\n\n- [x] Write the press release\n- [ ] Update the website\n- [ ] Contact the media \n\n~~The world is flat.~~\n\nThat is so funny! :joy: 🤮\n\n###### 🤮\n\nI need to highlight these ==very important words==. \n\nwesdf H~2~O sdf asf X^2^ \n\nem this is: *some italic type shit.*\n\nterm\n: definition \n\n```\n{\n  \"firstName\": \"John\",\n  \"lastName\": \"Smith\",\n  \"age\": 25\n}\n``` "),
        ];
    }
}
